// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommandStreamClient is the client API for CommandStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandStreamClient interface {
	// Opens a bidirectional streaming channel where:
	// - The Proxy sends commands (Request)
	// - The Node responds with events/data (Response)
	ListenCommands(ctx context.Context, opts ...grpc.CallOption) (CommandStream_ListenCommandsClient, error)
	// Returns a health report from the node, including:
	//   - basic liveness (status)
	//   - node mode (gateway, relay, etc.)
	//   - resource usage
	Health(ctx context.Context, in *Void, opts ...grpc.CallOption) (*HealthResponse, error)
	// Returns a list of all topics currently subscribed to
	// by the node in the pubsub network.
	ListTopics(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TopicList, error)
}

type commandStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandStreamClient(cc grpc.ClientConnInterface) CommandStreamClient {
	return &commandStreamClient{cc}
}

func (c *commandStreamClient) ListenCommands(ctx context.Context, opts ...grpc.CallOption) (CommandStream_ListenCommandsClient, error) {
	stream, err := c.cc.NewStream(ctx, &CommandStream_ServiceDesc.Streams[0], "/proto.CommandStream/ListenCommands", opts...)
	if err != nil {
		return nil, err
	}
	x := &commandStreamListenCommandsClient{stream}
	return x, nil
}

type CommandStream_ListenCommandsClient interface {
	Send(*Request) error
	Recv() (*Response, error)
	grpc.ClientStream
}

type commandStreamListenCommandsClient struct {
	grpc.ClientStream
}

func (x *commandStreamListenCommandsClient) Send(m *Request) error {
	return x.ClientStream.SendMsg(m)
}

func (x *commandStreamListenCommandsClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *commandStreamClient) Health(ctx context.Context, in *Void, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/proto.CommandStream/Health", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandStreamClient) ListTopics(ctx context.Context, in *Void, opts ...grpc.CallOption) (*TopicList, error) {
	out := new(TopicList)
	err := c.cc.Invoke(ctx, "/proto.CommandStream/ListTopics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandStreamServer is the server API for CommandStream service.
// All implementations must embed UnimplementedCommandStreamServer
// for forward compatibility
type CommandStreamServer interface {
	// Opens a bidirectional streaming channel where:
	// - The Proxy sends commands (Request)
	// - The Node responds with events/data (Response)
	ListenCommands(CommandStream_ListenCommandsServer) error
	// Returns a health report from the node, including:
	//   - basic liveness (status)
	//   - node mode (gateway, relay, etc.)
	//   - resource usage
	Health(context.Context, *Void) (*HealthResponse, error)
	// Returns a list of all topics currently subscribed to
	// by the node in the pubsub network.
	ListTopics(context.Context, *Void) (*TopicList, error)
	mustEmbedUnimplementedCommandStreamServer()
}

// UnimplementedCommandStreamServer must be embedded to have forward compatible implementations.
type UnimplementedCommandStreamServer struct {
}

func (UnimplementedCommandStreamServer) ListenCommands(CommandStream_ListenCommandsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListenCommands not implemented")
}
func (UnimplementedCommandStreamServer) Health(context.Context, *Void) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedCommandStreamServer) ListTopics(context.Context, *Void) (*TopicList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTopics not implemented")
}
func (UnimplementedCommandStreamServer) mustEmbedUnimplementedCommandStreamServer() {}

// UnsafeCommandStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandStreamServer will
// result in compilation errors.
type UnsafeCommandStreamServer interface {
	mustEmbedUnimplementedCommandStreamServer()
}

func RegisterCommandStreamServer(s grpc.ServiceRegistrar, srv CommandStreamServer) {
	s.RegisterService(&CommandStream_ServiceDesc, srv)
}

func _CommandStream_ListenCommands_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CommandStreamServer).ListenCommands(&commandStreamListenCommandsServer{stream})
}

type CommandStream_ListenCommandsServer interface {
	Send(*Response) error
	Recv() (*Request, error)
	grpc.ServerStream
}

type commandStreamListenCommandsServer struct {
	grpc.ServerStream
}

func (x *commandStreamListenCommandsServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *commandStreamListenCommandsServer) Recv() (*Request, error) {
	m := new(Request)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _CommandStream_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandStreamServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandStream/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandStreamServer).Health(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandStream_ListTopics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandStreamServer).ListTopics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CommandStream/ListTopics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandStreamServer).ListTopics(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

// CommandStream_ServiceDesc is the grpc.ServiceDesc for CommandStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommandStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CommandStream",
	HandlerType: (*CommandStreamServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _CommandStream_Health_Handler,
		},
		{
			MethodName: "ListTopics",
			Handler:    _CommandStream_ListTopics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListenCommands",
			Handler:       _CommandStream_ListenCommands_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/p2p_stream.proto",
}
