services:
  gateway-1:
    image: 'getoptimum/gateway:latest'
    ports:
      - "8081:8080"
    environment:
      - GATEWAY_PORT=:8080
      - CLUSTER_ID=gateway-1
      - ENABLE_AUTH=false # not using Auth0 for now if needed they pass AUTH0_DOMAIN and AUTH0_AUDIENCE
      - LOG_LEVEL=debug
      - P2P_NODES=p2pnode-1:33212,p2pnode-2:33212,p2pnode-3:33212,p2pnode-4:33212 # comma separated list of p2p node
    networks:
      optimum-network:
        ipv4_address: 172.28.0.10
    depends_on:
      - p2pnode-1
      - p2pnode-2
      - p2pnode-3
  gateway-2:
    image: 'getoptimum/gateway:latest'
    ports:
      - "8082:8080"
    environment:
      - GATEWAY_PORT=:8080
      - CLUSTER_ID=gateway-1
      - ENABLE_AUTH=false # not using Auth0
      - LOG_LEVEL=debug
      - P2P_NODES=p2pnode-1:33212,p2pnode-2:33212,p2pnode-3:33212,p2pnode-4:33212
    networks:
      optimum-network:
        ipv4_address: 172.28.0.11
    depends_on:
      - p2pnode-1
      - p2pnode-2
      - p2pnode-3

  p2pnode-1:
    image: 'getoptimum/p2pnode:latest'
    volumes:
      - ./identity:/identity
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_ID=p2pnode-1
      - NODE_MODE=optimum # options: "gossipsub", "optimum"
      - SIDECAR_PORT=33212 # default port for sidecar is 33212 for the grpc bidirectional streaming for the gateway
      - API_PORT=9090 # default port for API is 9090
      - IDENTITY_DIR=/identity
      # configuration for gossipsub
      # - GOSSIPSUB_PORT=6060 # default port for gossipsub is 6060
      # - GOSSIPSUB_MAX_MSG_SIZE=1048576 # 1MB
      # - GOSSIPSUB_MESH_TARGET=6 # number of peers to connect to default is 6
      # - GOSSIPSUB_MESH_MIN=3 # minimum number of peers to connect to default is 3
      # - GOSSIPSUB_MESH_MAX=12 # maximum number of peers to connect to default is 12
      - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/6060/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
      - OPTIMUM_PORT=7070 # default port for Optimum is 7070
      - OPTIMUM_MAX_MSG_SIZE=1048576 # 1MB
      - OPTIMUM_MESH_TARGET=6 # number of peers to connect to
      - OPTIMUM_MESH_MIN=3 # minimum number of peers to connect to
      - OPTIMUM_MESH_MAX=12 # maximum number of peers to connect to
      - OPTIMUM_SHARD_FACTOR=4 # number of shards to create default is 4
      - OPTIMUM_SHARD_MULT=1.5 # multiplier for shard size default is 1.5
      - OPTIMUM_THRESHOLD=0.75 # forward shred threshold default is 0.75
      - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/7070/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
    networks:
      optimum-network:
        ipv4_address: 172.28.0.12
    ports:
      - "33221:33212"
      - "7071:7070"
      - "6061:6060"
      - "9091:9090"

  p2pnode-2:
    image: 'getoptimum/p2pnode:latest'
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_ID=p2pnode-1
      - NODE_MODE=optimum # options: "gossipsub", "optimum"
      - SIDECAR_PORT=33212 # default port for sidecar is 33212
      - API_PORT=9090 # default port for API is 9090
      - IDENTITY_DIR=/identity
      # configuration for gossipsub
      # - GOSSIPSUB_PORT=6060 # default port for gossipsub is 6060
      # - GOSSIPSUB_MAX_MSG_SIZE=1048576 # 1MB
      # - GOSSIPSUB_MESH_TARGET=6 # number of peers to connect to default is 6
      # - GOSSIPSUB_MESH_MIN=3 # minimum number of peers to connect to default is 3
      # - GOSSIPSUB_MESH_MAX=12 # maximum number of peers to connect to default is 12
      - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/6060/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
      - OPTIMUM_PORT=7070 # default port for Optimum is 7070
      - OPTIMUM_MAX_MSG_SIZE=1048576 # 1MB
      - OPTIMUM_MESH_TARGET=6 # number of peers to connect to
      - OPTIMUM_MESH_MIN=3 # minimum number of peers to connect to
      - OPTIMUM_MESH_MAX=12 # maximum number of peers to connect to
      - OPTIMUM_SHARD_FACTOR=4 # number of shards to create default is 4
      - OPTIMUM_SHARD_MULT=1.5 # multiplier for shard size default is 1.5
      - OPTIMUM_THRESHOLD=0.75 # forward shred threshold default is 0.75
      - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/7070/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
    networks:
      optimum-network:
        ipv4_address: 172.28.0.13
    ports:
      - "33222:33212"
      - "7072:7070"
      - "6062:6060"
      - "9092:9090"

  p2pnode-3:
    image: 'getoptimum/p2pnode:latest'
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_ID=p2pnode-1
      - NODE_MODE=optimum # options: "gossipsub", "optimum"
      - SIDECAR_PORT=33212 # default port for sidecar is 33212
      - API_PORT=9090 # default port for API is 9090
      - IDENTITY_DIR=/identity
      # configuration for gossipsub
      # - GOSSIPSUB_PORT=6060 # default port for gossipsub is 6060
      # - GOSSIPSUB_MAX_MSG_SIZE=1048576 # 1MB
      # - GOSSIPSUB_MESH_TARGET=6 # number of peers to connect to
      # - GOSSIPSUB_MESH_MIN=3 # minimum number of peers to connect to
      # - GOSSIPSUB_MESH_MAX=12 # maximum number of peers to connect to
      # - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/6060/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
      - OPTIMUM_PORT=7070 # default port for Optimum is 7070
      - OPTIMUM_MAX_MSG_SIZE=1048576 # default is 1MB
      - OPTIMUM_MESH_TARGET=6 # number of peers to connect to default is 6
      - OPTIMUM_MESH_MIN=3 # minimum number of peers to connect to default is 3
      - OPTIMUM_MESH_MAX=12 # maximum number of peers to connect to default is 12
      - OPTIMUM_SHARD_FACTOR=4 # number of shards to create default is 4
      - OPTIMUM_SHARD_MULT=1.5 # multiplier for shard size default is 1.5
      - OPTIMUM_THRESHOLD=0.75 # forward shred threshold default is 0.75
      - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/7070/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
    networks:
      optimum-network:
        ipv4_address: 172.28.0.14
    ports:
      - "33223:33212"
      - "7073:7070"
      - "6063:6060"
      - "9093:9090"

  p2pnode-4:
    image: 'getoptimum/p2pnode:latest'
    environment:
      - LOG_LEVEL=debug
      - CLUSTER_ID=p2pnode-1
      - NODE_MODE=optimum # options: "gossipsub", "optimum"
      - SIDECAR_PORT=33212 # default port for sidecar is 33212
      - API_PORT=9090 # default port for API is 9090
      - IDENTITY_DIR=/identity
      # configuration for gossipsub
      # - GOSSIPSUB_PORT=6060 # default port for gossipsub is 6060
      # - GOSSIPSUB_MAX_MSG_SIZE=1048576 # 1MB
      # - GOSSIPSUB_MESH_TARGET=6 # number of peers to connect to
      # - GOSSIPSUB_MESH_MIN=3 # minimum number of peers to connect to
      # - GOSSIPSUB_MESH_MAX=12 # maximum number of peers to connect to
      # - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/6060/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
      - OPTIMUM_PORT=7070 # default port for Optimum is 7070
      - OPTIMUM_MAX_MSG_SIZE=1048576 # 1MB
      - OPTIMUM_MESH_TARGET=6 # number of peers to connect to
      - OPTIMUM_MESH_MIN=3 # minimum number of peers to connect to
      - OPTIMUM_MESH_MAX=12 # maximum number of peers to connect to
      - OPTIMUM_SHARD_FACTOR=4 # number of shards to create default is 4
      - OPTIMUM_SHARD_MULT=1.5 # multiplier for shard size default is 1.5
      - OPTIMUM_THRESHOLD=0.75 # forward shred threshold default is 0.75
      - BOOTSTRAP_PEERS=/ip4/172.28.0.12/tcp/7070/p2p/${BOOTSTRAP_PEER_ID} # multiple bootstrap peers can be specified
    networks:
      optimum-network:
        ipv4_address: 172.28.0.15
    ports:
      - "33224:33212"
      - "7074:7070"
      - "6064:6060"
      - "9094:9090"

networks:
  optimum-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16