{
 "title": "mump2p Nodes Dashboard",
 "tags": [
  "optimum",
  "v0.0.1-rc8",
  "testnet"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Total number of mump2p peers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "optimum_mump2p_total_peers{cluster_id=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "System state", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * ( go_memstats_heap_idle_bytes{cluster_id=\"$cluster\", protocol_type=\"optimum\"} / go_memstats_heap_sys_bytes{cluster_id=\"$cluster\", protocol_type=\"optimum\"} )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "allocated memory by process",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{cluster_id=\"$cluster\", protocol_type=\"optimum\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Nodes distribution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes Distribution",
     "type": "geomap",
     "gridPos": { "h": 17, "w": 11, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "optimum_det_coordinates_geo_location{cluster_id=\"$cluster\", protocol_type=\"optimum\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Nodes distribution",
     "type": "table",
     "gridPos": { "h": 17, "w": 13, "x": 11, "y": 72 },
     "targets": [
      {
       "expr": "max by(instance, country_iso, latitude, longitude, protocol_type) (optimum_det_coordinates_geo_location{cluster_id=\"$cluster\", protocol_type=\"optimum\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Shard info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Total Shards Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(optimum_mump2p_shards_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unhelpful Shards",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 48 },
   "targets": [
    {
     "expr": "rate(optimum_mump2p_shards_unhelpful_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Unnecessary Shards Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate (optimum_mump2p_shards_unnecessary_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "percent of unnecessary shards %",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by(instance) (optimum_mump2p_shards_unnecessary_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}) / sum by(instance) (optimum_mump2p_shards_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "P2P stat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "total bytes ",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (optimum_bandwidth_total_bytes{cluster_id=\"$cluster\", protocol_type=\"optimum\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "published messages per node",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 78 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (optimum_bandwidth_messages_total{cluster_id=\"$cluster\", protocol_type=\"optimum\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}