{
 "title": "Optimum Proxy Dashboard",
 "tags": [
  "optimum",
  "v0.0.1-rc8",
  "testnet"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster_id)" } }
  ]
 },
 "panels": [
  { "title": "Cluster Nodes Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Proxy Nodes Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"proxies\", cluster_id=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "mump2p Nodes Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"p2p-nodes\", cluster_id=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{cluster_id=~\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Go Thread Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "go_threads{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "go_goroutines{cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Proxy Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Proxy Active Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodes_active_total{job=\"proxies\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Topics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "optimum_p2p_active_topics{cluster_id=\"$cluster\", job=\"p2p-nodes\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active WebSocket Clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "optimum_proxy_ws_clients_active{job=\"proxies\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active gRPC Clients (TODO))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "optimum_proxy_ws_clients_active{job=\"proxies\", cluster_id=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages Published by Client",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(client_id, topic) (rate(optimum_proxy_published_by_client_total{job=\"proxies\", cluster_id=~\"$cluster\"}[5m]))",
     "legendFormat": "{{client_id}} {{topic}}"
    }
   ]
  },
  {
   "title": "Messages Published Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(topic) (rate(optimum_p2p_messages_published_total{cluster_id=~\"$cluster\"}[5m]))",
     "legendFormat": "{{client_id}} {{topic}}"
    }
   ]
  },
  {
   "title": "Message Delivery Latency (P95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(delivered_messages_delay_seconds_bucket{cluster_id=~\"$cluster\"}[5m])) by (le))",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Publish Errors (last 5m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(publish_error_total{cluster_id=~\"$cluster\"}[5m])"
    }
   ]
  }
 ]
}