import sys
import argparse
import os
from collections import defaultdict

def percentile(data, p):
    """
    Calculate the precise percentile of a given data list.
    Args:
        data (list): A list of numerical values (latencies).
        p (float): The target percentile (e.g., 99 for P99).
    Returns:
        float: The calculated percentile value.
    """
    if not data:
        return 0.0
    data = sorted(data)
    n = len(data)

    # Calculate the ideal fractional index for the target percentile
    k = (n - 1) * (p / 100.0)
    f = int(k)
    c = int(k) + 1 if int(k) + 1 < n else f

    # If the index is exactly an integer, return the value at that index
    if f == c:
        return data[f]
    
    # Linear interpolation for values falling between indices
    d0 = data[f] * (c - k)
    d1 = data[c] * (k - f)
    return d0 + d1

def main():
    # Setup command-line argument parsing
    parser = argparse.ArgumentParser(description="Calculate P2P Propagation Latency (K8s version)")
    parser.add_argument("--file", default="incoming-trace.tsv", help="Path to the trace file generated by the subscriber")
    parser.add_argument("--data-file", help="Path to data file (ignored in this stripped-down K8s version)")
    parser.add_argument("--skip", type=int, default=5, help="Number of initial messages to discard to account for warm-up time")
    parser.add_argument("--msg-size", type=str, help="Message payload size used for labeling the output report")
    args = parser.parse_args()

    target_file = args.file

    # Ensure the trace file exists before attempting to read
    if not os.path.exists(target_file):
        print(f"Error: File '{target_file}' not found.")
        sys.exit(1)

    print(f"Reading data from {target_file}...\n")
    
    # msg_timestamps will map a message ID (msg_id) to a list of delivery timestamps
    msg_timestamps = defaultdict(list)
    
    try:
        # Parse the trace file line by line
        with open(target_file, 'r') as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                
                parts = line.split('\t')
                # Ensure the line has enough columns
                if len(parts) >= 6:
                    event = parts[0]
                    # We are only interested in 'DELIVER_MESSAGE' events for latency calculation
                    if event == "DELIVER_MESSAGE":
                        msg_id = parts[3]
                        try:
                            # The delivery timestamp (in nanoseconds) is expected in the 6th column
                            timestamp = int(parts[5])
                            msg_timestamps[msg_id].append(timestamp)
                        except ValueError:
                            # Ignore rows where the timestamp is not a valid integer
                            pass
    except Exception as e:
        print(f"Error reading file: {e}")
        return

    if not msg_timestamps:
        print("No DELIVER_MESSAGE events found (or file is empty/invalid).")
        return

    # Process timestamps to calculate latency for each distinct message
    results = []
    for msg_id, t_list in msg_timestamps.items():
        if not t_list:
            continue
        
        # Calculate propagation delay: Latest delivery time minus earliest delivery time
        t_start = min(t_list)
        t_end = max(t_list)
        latency_ns = t_end - t_start
        latency_ms = latency_ns / 1_000_000.0 # Convert nanoseconds to milliseconds
        node_count = len(t_list) 
        
        results.append({
            "msg_id": msg_id,
            "t_start": t_start,
            "latency_ms": latency_ms,
            "node_count": node_count
        })

    # Sort the results chronologically based on when the message was first seen
    results = sorted(results, key=lambda x: x["t_start"])
    total_msgs = len(results)
    
    print(f"Discovered a total of {total_msgs} distinct test messages.")

    # Discard warm-up messages to avoid skewed results from initial network discovery
    if total_msgs > args.skip:
        valid_msgs = results[args.skip:]
        print(f"Discarding the first {args.skip} warm-up messages. Using the remaining {len(valid_msgs)} messages for statistical analysis.\n")
    else:
        print(f"Warning: Total messages ({total_msgs}) is less than or equal to the number of skipped warm-up messages ({args.skip}). Using all messages.")
        valid_msgs = results

    if not valid_msgs:
        return

    latencies = [x["latency_ms"] for x in valid_msgs]
    
    mean_latency = sum(latencies) / len(latencies)
    max_latency = max(latencies)
    p50 = percentile(latencies, 50)
    p90 = percentile(latencies, 90)
    p95 = percentile(latencies, 95)
    p99 = percentile(latencies, 99)

    print("\n=== P2P Network Propagation Latency Summary ===")
    if args.msg_size:
        print(f"Message Size (Payload)     : {args.msg_size} bytes")
    print(f"Sample Size (after filter) : {len(latencies)} messages")
    print(f"Mean Latency               : {mean_latency:.2f} ms")
    print(f"P50 Latency (Median)       : {p50:.2f} ms")
    print(f"P90 Latency                : {p90:.2f} ms")
    print(f"P95 Latency                : {p95:.2f} ms")
    print(f"P99 Latency                : {p99:.2f} ms")
    print(f"Maximum Latency            : {max_latency:.2f} ms")
    print("===============================================")

    # Display the top 5 worst-performing messages
    print("\n--- Top 5 Outlier Messages (Highest Latency) ---")
    outliers = sorted(valid_msgs, key=lambda x: x['latency_ms'], reverse=True)[:5]
    for i, m in enumerate(outliers):
        print(f"{i+1}. Latency: {m['latency_ms']:.2f} ms | MsgID: {m['msg_id']}")

if __name__ == "__main__":
    main()
